import { createContext, useContext, useState, type ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  en: {
    nav_home: 'Home',
    nav_services: 'Services',
    nav_contact: 'Contact',
    hero_title: 'Your Gateway to German Ausbildung',
    hero_subtitle: 'Professional vocational training support tailored for your success in Germany.',
    hero_cta: 'Get Started',
    hero_scroll: 'Explore Services',
    services_title: 'Our Services',
    services_subtitle: 'Three comprehensive solutions to guide you through every step of your Ausbildung journey.',
    service1_title: 'Complete Dossier Analysis',
    service1_desc: 'Thorough evaluation of your documents and qualifications to identify strengths and areas for improvement.',
    service1_duration: '48 - 72 hours',
    service2_title: 'Professional Dossier Creation',
    service2_desc: 'Expert crafting of your complete application dossier with compelling presentation and formatting.',
    service2_duration: '5 days',
    service3_title: 'Full Application Management',
    service3_desc: 'End-to-end management of your applications with continuous tracking and follow-up support.',
    service3_duration: '3 months tracking',
    form_title: 'Start Your Journey',
    form_subtitle: 'Select a service and provide your details. Our team will contact you within 24 hours.',
    form_service_label: 'Select Service',
    form_name_label: 'Full Name',
    form_email_label: 'Email Address',
    form_phone_label: 'Phone Number',
    form_docs_label: 'Upload Documents',
    form_docs_hint: 'PDF, JPG, PNG up to 10MB',
    form_submit: 'Submit Request',
    form_success: 'Thank you! We will contact you shortly.',
    footer_rights: 'All rights reserved.',
    footer_tagline: 'Your trusted partner for Ausbildung success.',
    lang_en: 'EN',
    lang_fr: 'FR',
    lang_ar: 'AR',
    why_title: 'Why Choose BM27?',
    why_1_title: 'Expert Guidance',
    why_1_desc: 'Years of experience in German vocational training applications.',
    why_2_title: 'Fast Turnaround',
    why_2_desc: 'Quick and efficient processing of all your documents.',
    why_3_title: 'High Success Rate',
    why_3_desc: 'Proven track record of successful Ausbildung placements.',
    why_4_title: 'Personalized Support',
    why_4_desc: 'Dedicated assistance tailored to your unique profile.',
    testimonial_title: 'Success Stories',
    testimonial_1: 'BM27 helped me secure my Ausbildung in record time. Their professionalism is unmatched.',
    testimonial_1_name: 'Ahmed K.',
    testimonial_1_role: 'IT Specialist Trainee',
    testimonial_2: 'The dossier creation service was exceptional. Every detail was perfectly handled.',
    testimonial_2_name: 'Fatima B.',
    testimonial_2_role: 'Nursing Trainee',
    testimonial_3: 'Their application management gave me peace of mind throughout the entire process.',
    testimonial_3_name: 'Karim M.',
    testimonial_3_role: 'Mechanical Engineer Trainee',
    contact_title: 'Get In Touch',
    contact_email: 'contact@bm27services.com',
    contact_phone: '+49 123 456 7890',
    contact_address: 'Berlin, Germany',
    process_title: 'Our Process',
    process_step1: 'Initial Consultation',
    process_step2: 'Document Review',
    process_step3: 'Dossier Preparation',
    process_step4: 'Application Submission',
    process_step5: 'Follow-up & Support',
  },
  fr: {
    nav_home: 'Accueil',
    nav_services: 'Services',
    nav_contact: 'Contact',
    hero_title: 'Votre Passerelle vers l\'Ausbildung Allemande',
    hero_subtitle: 'Un accompagnement professionnel pour votre formation professionnelle en Allemagne.',
    hero_cta: 'Commencer',
    hero_scroll: 'Découvrir les Services',
    services_title: 'Nos Services',
    services_subtitle: 'Trois solutions complètes pour vous guider à chaque étape de votre parcours Ausbildung.',
    service1_title: 'Analyse Complète du Dossier',
    service1_desc: 'Évaluation approfondie de vos documents et qualifications pour identifier les forces et les axes d\'amélioration.',
    service1_duration: '48 - 72 heures',
    service2_title: 'Création Professionnelle du Dossier',
    service2_desc: 'Rédaction experte de votre dossier de candidature complet avec une présentation convaincante.',
    service2_duration: '5 jours',
    service3_title: 'Gestion Complète des Candidatures',
    service3_desc: 'Gestion de bout en bout de vos candidatures avec suivi continu et support de suivi.',
    service3_duration: 'Suivi de 3 mois',
    form_title: 'Commencez Votre Parcours',
    form_subtitle: 'Sélectionnez un service et fournissez vos coordonnées. Notre équipe vous contactera sous 24 heures.',
    form_service_label: 'Sélectionner le Service',
    form_name_label: 'Nom Complet',
    form_email_label: 'Adresse Email',
    form_phone_label: 'Numéro de Téléphone',
    form_docs_label: 'Télécharger les Documents',
    form_docs_hint: 'PDF, JPG, PNG jusqu\'à 10 Mo',
    form_submit: 'Envoyer la Demande',
    form_success: 'Merci ! Nous vous contacterons sous peu.',
    footer_rights: 'Tous droits réservés.',
    footer_tagline: 'Votre partenaire de confiance pour la réussite de votre Ausbildung.',
    lang_en: 'EN',
    lang_fr: 'FR',
    lang_ar: 'AR',
    why_title: 'Pourquoi Choisir BM27 ?',
    why_1_title: 'Conseil Expert',
    why_1_desc: 'Années d\'expérience dans les candidatures de formation professionnelle allemande.',
    why_2_title: 'Rapidité d\'Exécution',
    why_2_desc: 'Traitement rapide et efficace de tous vos documents.',
    why_3_title: 'Taux de Réussite Élevé',
    why_3_desc: 'Historique prouvé de placements Ausbildung réussis.',
    why_4_title: 'Support Personnalisé',
    why_4_desc: 'Assistance dédiée adaptée à votre profil unique.',
    testimonial_title: 'Témoignages',
    testimonial_1: 'BM27 m\'a aidé à obtenir mon Ausbildung en un temps record. Leur professionnalisme est inégalé.',
    testimonial_1_name: 'Ahmed K.',
    testimonial_1_role: 'Stagiaire Spécialiste IT',
    testimonial_2: 'Le service de création de dossier était exceptionnel. Chaque détail a été parfaitement géré.',
    testimonial_2_name: 'Fatima B.',
    testimonial_2_role: 'Stagiaire en Soins Infirmiers',
    testimonial_3: 'Leur gestion des candidatures m\'a donné la tranquillité d\'esprit tout au long du processus.',
    testimonial_3_name: 'Karim M.',
    testimonial_3_role: 'Stagiaire Ingénieur Mécanique',
    contact_title: 'Contactez-Nous',
    contact_email: 'contact@bm27services.com',
    contact_phone: '+49 123 456 7890',
    contact_address: 'Berlin, Allemagne',
    process_title: 'Notre Processus',
    process_step1: 'Consultation Initiale',
    process_step2: 'Examen des Documents',
    process_step3: 'Préparation du Dossier',
    process_step4: 'Soumission de la Candidature',
    process_step5: 'Suivi & Support',
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_services: 'الخدمات',
    nav_contact: 'اتصل بنا',
    hero_title: 'بوابتك إلى التدريب المهني الألماني',
    hero_subtitle: 'دعم مهني متخصص للتدريب المهني في ألمانيا مصمم لنجاحك.',
    hero_cta: 'ابدأ الآن',
    hero_scroll: 'استكشف الخدمات',
    services_title: 'خدماتنا',
    services_subtitle: 'ثلاث حلول شاملة لإرشادك في كل خطوة من رحلتك التدريبية.',
    service1_title: 'تحليل شامل للملف',
    service1_desc: 'تقييم شامل لمستنداتك ومؤهلاتك لتحديد نقاط القوة ومجالات التحسين.',
    service1_duration: '48 - 72 ساعة',
    service2_title: 'إنشاء احترافي للملف',
    service2_desc: 'صياغة خبيرة لملف طلبك الكامل مع عرض مقنع وتنسيق احترافي.',
    service2_duration: '5 أيام',
    service3_title: 'إدارة كاملة للطلبات',
    service3_desc: 'إدارة شاملة لطلباتك مع تتبع مستمر ودعم متابع.',
    service3_duration: 'متابعة 3 أشهر',
    form_title: 'ابدأ رحلتك',
    form_subtitle: 'اختر خدمة وقدم بياناتك. سيتواصل معك فريقنا خلال 24 ساعة.',
    form_service_label: 'اختر الخدمة',
    form_name_label: 'الاسم الكامل',
    form_email_label: 'عنوان البريد الإلكتروني',
    form_phone_label: 'رقم الهاتف',
    form_docs_label: 'رفع المستندات',
    form_docs_hint: 'PDF, JPG, PNG حتى 10 ميجابايت',
    form_submit: 'إرسال الطلب',
    form_success: 'شكراً لك! سنتواصل معك قريباً.',
    footer_rights: 'جميع الحقوق محفوظة.',
    footer_tagline: 'شريكك الموثوق لنجاح التدريب المهني.',
    lang_en: 'EN',
    lang_fr: 'FR',
    lang_ar: 'AR',
    why_title: 'لماذا تختار BM27؟',
    why_1_title: 'إرشاد خبير',
    why_1_desc: 'سنوات من الخبرة في طلبات التدريب المهني الألماني.',
    why_2_title: 'سرعة التنفيذ',
    why_2_desc: 'معالجة سريعة وفعالة لجميع مستنداتك.',
    why_3_title: 'معدل نجاح مرتفع',
    why_3_desc: 'سجل حافل من التدريبات المهنية الناجحة.',
    why_4_title: 'دعم مخصص',
    why_4_desc: 'مساعدة مخصصة مصممة حسب ملفك الشخصي الفريد.',
    testimonial_title: 'قصص النجاح',
    testimonial_1: 'ساعدني BM27 في الحصول على تدريبي المهني في وقت قياسي. احترافيتهم لا مثيل لها.',
    testimonial_1_name: 'أحمد ك.',
    testimonial_1_role: 'متدرب متخصص في تكنولوجيا المعلومات',
    testimonial_2: 'كانت خدمة إنشاء الملف استثنائية. تم التعامل مع كل تفصيل بإتقان.',
    testimonial_2_name: 'فاطمة ب.',
    testimonial_2_role: 'متدربة في التمريض',
    testimonial_3: 'أعطتني إدارة طلباتهم راحة البال طوال العملية بأكملها.',
    testimonial_3_name: 'كريم م.',
    testimonial_3_role: 'متدرب هندسة ميكانيكية',
    contact_title: 'تواصل معنا',
    contact_email: 'contact@bm27services.com',
    contact_phone: '+49 123 456 7890',
    contact_address: 'برلين، ألمانيا',
    process_title: 'عمليتنا',
    process_step1: 'الاستشارة الأولية',
    process_step2: 'مراجعة المستندات',
    process_step3: 'إعداد الملف',
    process_step4: 'تقديم الطلب',
    process_step5: 'المتابعة والدعم',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const isRTL = language === 'ar';

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
